"""creacion_inicial_tablas_facturacion_y_catalogos_siat

Revision ID: 2cca4027c43a
Revises: 
Create Date: 2025-06-01 04:40:35.586248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cca4027c43a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades_economicas_siat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_clasificador', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actividades_economicas_siat_codigo_clasificador'), 'actividades_economicas_siat', ['codigo_clasificador'], unique=True)
    op.create_index(op.f('ix_actividades_economicas_siat_id'), 'actividades_economicas_siat', ['id'], unique=False)
    op.create_table('documentos_sector_siat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_clasificador', sa.String(length=5), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_sector_siat_codigo_clasificador'), 'documentos_sector_siat', ['codigo_clasificador'], unique=True)
    op.create_index(op.f('ix_documentos_sector_siat_id'), 'documentos_sector_siat', ['id'], unique=False)
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_index(op.f('ix_empresas_nit'), 'empresas', ['nit'], unique=True)
    op.create_table('metodos_pago_siat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_clasificador', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metodos_pago_siat_codigo_clasificador'), 'metodos_pago_siat', ['codigo_clasificador'], unique=True)
    op.create_index(op.f('ix_metodos_pago_siat_id'), 'metodos_pago_siat', ['id'], unique=False)
    op.create_table('motivos_anulacion_siat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_clasificador', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_motivos_anulacion_siat_codigo_clasificador'), 'motivos_anulacion_siat', ['codigo_clasificador'], unique=True)
    op.create_index(op.f('ix_motivos_anulacion_siat_id'), 'motivos_anulacion_siat', ['id'], unique=False)
    op.create_table('tipos_documento_identidad_siat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_clasificador', sa.String(length=5), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_documento_identidad_siat_codigo_clasificador'), 'tipos_documento_identidad_siat', ['codigo_clasificador'], unique=True)
    op.create_index(op.f('ix_tipos_documento_identidad_siat_id'), 'tipos_documento_identidad_siat', ['id'], unique=False)
    op.create_table('tipos_emision_siat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_clasificador', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_emision_siat_codigo_clasificador'), 'tipos_emision_siat', ['codigo_clasificador'], unique=True)
    op.create_index(op.f('ix_tipos_emision_siat_id'), 'tipos_emision_siat', ['id'], unique=False)
    op.create_table('tipos_factura_siat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_clasificador', sa.String(length=5), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_factura_siat_codigo_clasificador'), 'tipos_factura_siat', ['codigo_clasificador'], unique=True)
    op.create_index(op.f('ix_tipos_factura_siat_id'), 'tipos_factura_siat', ['id'], unique=False)
    op.create_table('tipos_moneda_siat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_clasificador', sa.String(length=5), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_moneda_siat_codigo_clasificador'), 'tipos_moneda_siat', ['codigo_clasificador'], unique=True)
    op.create_index(op.f('ix_tipos_moneda_siat_id'), 'tipos_moneda_siat', ['id'], unique=False)
    op.create_table('unidades_medida_siat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_clasificador', sa.String(length=5), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unidades_medida_siat_codigo_clasificador'), 'unidades_medida_siat', ['codigo_clasificador'], unique=True)
    op.create_index(op.f('ix_unidades_medida_siat_id'), 'unidades_medida_siat', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_cliente_erp', sa.String(length=20), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('codigo_tipo_documento_identidad', sa.String(length=5), nullable=False),
    sa.Column('complemento', sa.String(length=10), nullable=True),
    sa.Column('nombre_razon_social', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_tipo_documento_identidad'], ['tipos_documento_identidad_siat.codigo_clasificador'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_codigo_cliente_erp'), 'clientes', ['codigo_cliente_erp'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_numero_documento'), 'clientes', ['numero_documento'], unique=False)
    op.create_table('sucursales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('codigo_sucursal_siat', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('direccion', sa.String(length=500), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo_sucursal_siat', name='uq_empresa_codigo_sucursal')
    )
    op.create_index(op.f('ix_sucursales_id'), 'sucursales', ['id'], unique=False)
    op.create_table('puntos_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('codigo_punto_venta_siat', sa.Integer(), nullable=False),
    sa.Column('nombre_punto_venta', sa.String(length=255), nullable=True),
    sa.Column('tipo_punto_venta_siat', sa.String(length=50), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sucursal_id', 'codigo_punto_venta_siat', name='uq_sucursal_codigo_punto_venta')
    )
    op.create_index(op.f('ix_puntos_venta_id'), 'puntos_venta', ['id'], unique=False)
    op.create_table('cufd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('punto_venta_id', sa.Integer(), nullable=False),
    sa.Column('codigo_cufd', sa.String(length=100), nullable=False),
    sa.Column('codigo_control', sa.String(length=50), nullable=False),
    sa.Column('direccion_siat', sa.String(length=500), nullable=False),
    sa.Column('fecha_vigencia', sa.DateTime(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['punto_venta_id'], ['puntos_venta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_cufd')
    )
    op.create_index(op.f('ix_cufd_id'), 'cufd', ['id'], unique=False)
    op.create_table('cuis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('punto_venta_id', sa.Integer(), nullable=False),
    sa.Column('codigo_cuis', sa.String(length=100), nullable=False),
    sa.Column('fecha_vigencia', sa.DateTime(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['punto_venta_id'], ['puntos_venta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_cuis')
    )
    op.create_index(op.f('ix_cuis_id'), 'cuis', ['id'], unique=False)
    op.create_table('eventos_contingencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('punto_venta_id', sa.Integer(), nullable=False),
    sa.Column('codigo_evento_siat', sa.String(length=100), nullable=True),
    sa.Column('codigo_motivo_evento_siat', sa.String(length=50), nullable=False),
    sa.Column('descripcion_evento', sa.String(length=500), nullable=False),
    sa.Column('fecha_hora_inicio_evento', sa.DateTime(), nullable=False),
    sa.Column('fecha_hora_fin_evento', sa.DateTime(), nullable=True),
    sa.Column('cufd_evento_contingencia', sa.String(length=255), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['punto_venta_id'], ['puntos_venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_contingencia_id'), 'eventos_contingencia', ['id'], unique=False)
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('punto_venta_id', sa.Integer(), nullable=False),
    sa.Column('cufd_id', sa.Integer(), nullable=False),
    sa.Column('numero_factura', sa.Integer(), nullable=False),
    sa.Column('cuf', sa.String(length=100), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=17, scale=2), nullable=False),
    sa.Column('monto_descuento', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('monto_gift_card', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('monto_total_sujeto_iva', sa.Numeric(precision=17, scale=2), nullable=False),
    sa.Column('codigo_metodo_pago_siat', sa.String(length=10), nullable=False),
    sa.Column('numero_tarjeta', sa.String(length=16), nullable=True),
    sa.Column('codigo_moneda_siat', sa.String(length=5), nullable=False),
    sa.Column('tipo_cambio', sa.Numeric(precision=17, scale=2), nullable=False),
    sa.Column('leyenda', sa.String(length=500), nullable=False),
    sa.Column('usuario_emisor', sa.String(length=100), nullable=False),
    sa.Column('codigo_documento_sector', sa.String(length=5), nullable=False),
    sa.Column('codigo_tipo_factura_siat', sa.String(length=5), nullable=False),
    sa.Column('codigo_tipo_emision_siat', sa.String(length=10), nullable=False),
    sa.Column('cafc', sa.String(length=50), nullable=True),
    sa.Column('codigo_excepcion_siat', sa.Integer(), nullable=True),
    sa.Column('xml_generado', sa.Text(), nullable=True),
    sa.Column('xml_firmado_enviado', sa.Text(), nullable=True),
    sa.Column('hash_xml_enviado', sa.String(length=64), nullable=True),
    sa.Column('fecha_envio_siat', sa.DateTime(), nullable=True),
    sa.Column('respuesta_siat', sa.Text(), nullable=True),
    sa.Column('codigo_estado_siat', sa.String(length=50), nullable=True),
    sa.Column('anulada', sa.Boolean(), nullable=True),
    sa.Column('fecha_anulacion', sa.DateTime(), nullable=True),
    sa.Column('codigo_motivo_anulacion_siat', sa.String(length=10), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['codigo_documento_sector'], ['documentos_sector_siat.codigo_clasificador'], ),
    sa.ForeignKeyConstraint(['codigo_metodo_pago_siat'], ['metodos_pago_siat.codigo_clasificador'], ),
    sa.ForeignKeyConstraint(['codigo_moneda_siat'], ['tipos_moneda_siat.codigo_clasificador'], ),
    sa.ForeignKeyConstraint(['codigo_motivo_anulacion_siat'], ['motivos_anulacion_siat.codigo_clasificador'], ),
    sa.ForeignKeyConstraint(['codigo_tipo_emision_siat'], ['tipos_emision_siat.codigo_clasificador'], ),
    sa.ForeignKeyConstraint(['codigo_tipo_factura_siat'], ['tipos_factura_siat.codigo_clasificador'], ),
    sa.ForeignKeyConstraint(['cufd_id'], ['cufd.id'], ),
    sa.ForeignKeyConstraint(['punto_venta_id'], ['puntos_venta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('punto_venta_id', 'numero_factura', 'cufd_id', name='uq_pv_numfact_cufd')
    )
    op.create_index(op.f('ix_facturas_cuf'), 'facturas', ['cuf'], unique=True)
    op.create_index(op.f('ix_facturas_id'), 'facturas', ['id'], unique=False)
    op.create_table('detalles_factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('actividad_economica_siat', sa.String(length=10), nullable=False),
    sa.Column('codigo_producto_sin_siat', sa.Integer(), nullable=False),
    sa.Column('codigo_producto_empresa', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=17, scale=5), nullable=False),
    sa.Column('unidad_medida_siat', sa.String(length=5), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=17, scale=2), nullable=False),
    sa.Column('monto_descuento_detalle', sa.Numeric(precision=17, scale=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=17, scale=2), nullable=False),
    sa.Column('numero_serie', sa.String(length=1500), nullable=True),
    sa.Column('numero_imei', sa.String(length=1500), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actividad_economica_siat'], ['actividades_economicas_siat.codigo_clasificador'], ),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['unidad_medida_siat'], ['unidades_medida_siat.codigo_clasificador'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalles_factura_id'), 'detalles_factura', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalles_factura_id'), table_name='detalles_factura')
    op.drop_table('detalles_factura')
    op.drop_index(op.f('ix_facturas_id'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_cuf'), table_name='facturas')
    op.drop_table('facturas')
    op.drop_index(op.f('ix_eventos_contingencia_id'), table_name='eventos_contingencia')
    op.drop_table('eventos_contingencia')
    op.drop_index(op.f('ix_cuis_id'), table_name='cuis')
    op.drop_table('cuis')
    op.drop_index(op.f('ix_cufd_id'), table_name='cufd')
    op.drop_table('cufd')
    op.drop_index(op.f('ix_puntos_venta_id'), table_name='puntos_venta')
    op.drop_table('puntos_venta')
    op.drop_index(op.f('ix_sucursales_id'), table_name='sucursales')
    op.drop_table('sucursales')
    op.drop_index(op.f('ix_clientes_numero_documento'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_codigo_cliente_erp'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_unidades_medida_siat_id'), table_name='unidades_medida_siat')
    op.drop_index(op.f('ix_unidades_medida_siat_codigo_clasificador'), table_name='unidades_medida_siat')
    op.drop_table('unidades_medida_siat')
    op.drop_index(op.f('ix_tipos_moneda_siat_id'), table_name='tipos_moneda_siat')
    op.drop_index(op.f('ix_tipos_moneda_siat_codigo_clasificador'), table_name='tipos_moneda_siat')
    op.drop_table('tipos_moneda_siat')
    op.drop_index(op.f('ix_tipos_factura_siat_id'), table_name='tipos_factura_siat')
    op.drop_index(op.f('ix_tipos_factura_siat_codigo_clasificador'), table_name='tipos_factura_siat')
    op.drop_table('tipos_factura_siat')
    op.drop_index(op.f('ix_tipos_emision_siat_id'), table_name='tipos_emision_siat')
    op.drop_index(op.f('ix_tipos_emision_siat_codigo_clasificador'), table_name='tipos_emision_siat')
    op.drop_table('tipos_emision_siat')
    op.drop_index(op.f('ix_tipos_documento_identidad_siat_id'), table_name='tipos_documento_identidad_siat')
    op.drop_index(op.f('ix_tipos_documento_identidad_siat_codigo_clasificador'), table_name='tipos_documento_identidad_siat')
    op.drop_table('tipos_documento_identidad_siat')
    op.drop_index(op.f('ix_motivos_anulacion_siat_id'), table_name='motivos_anulacion_siat')
    op.drop_index(op.f('ix_motivos_anulacion_siat_codigo_clasificador'), table_name='motivos_anulacion_siat')
    op.drop_table('motivos_anulacion_siat')
    op.drop_index(op.f('ix_metodos_pago_siat_id'), table_name='metodos_pago_siat')
    op.drop_index(op.f('ix_metodos_pago_siat_codigo_clasificador'), table_name='metodos_pago_siat')
    op.drop_table('metodos_pago_siat')
    op.drop_index(op.f('ix_empresas_nit'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_table('empresas')
    op.drop_index(op.f('ix_documentos_sector_siat_id'), table_name='documentos_sector_siat')
    op.drop_index(op.f('ix_documentos_sector_siat_codigo_clasificador'), table_name='documentos_sector_siat')
    op.drop_table('documentos_sector_siat')
    op.drop_index(op.f('ix_actividades_economicas_siat_id'), table_name='actividades_economicas_siat')
    op.drop_index(op.f('ix_actividades_economicas_siat_codigo_clasificador'), table_name='actividades_economicas_siat')
    op.drop_table('actividades_economicas_siat')
    # ### end Alembic commands ###
